### ISSUE TITLE
Review krill inversion code

### ISSUE THREAD

**Issue by leewujung** [uw-echospace/EchoPro#107]
Review krill inversion code.

Main goals are to clarify the below components:
- [x] What input files are required - [answer](https://github.com/uw-echospace/EchoPro/issues/107#issuecomment-1741851482)
- [x] What output files are generated - [answer](https://github.com/uw-echospace/EchoPro/issues/107#issuecomment-1741851482)
- [x] What are the data pre-processing steps before inversion? - [answer](https://github.com/uw-echospace/EchoPro/issues/107#issuecomment-1741846216)
- [x] What scattering model(s) are used - [answer](https://github.com/uw-echospace/EchoPro/issues/107#issuecomment-1741950533)
- [x] What inversion algorithm(s) does the code use - [answer](https://github.com/uw-echospace/EchoPro/issues/107#issuecomment-1741673915)

References here are:
- Matlab code for 2020 processing
- Basic documentation of processing steps: https://docs.google.com/document/d/10PsW2ZiQvZAQGtDJU-_1xYX6Hh8PC7pW/edit

**Comment by leewujung** [comment]
Inversion algorithm used: Matlab [lsqnonlin](https://www.mathworks.com/help/optim/ug/lsqnonlin.html)

**Comment by leewujung** [comment]
> What are the data pre-processing before inversion?

- Restructure Echoview NASC exports --> save as organized `.mat` files with names like `US-euph-2019 hake survey.mat`
- Extract relevant data values for inversion
  - Output data in xlsx: Sv mean, std, median, std of median (med_std), layer depth, layer thickness, effective volume, lat/lon
  - First round of clean up:
    ```python
    for tr in transects:  # loop through all transects (files)
       for f in freq:  # loop through all available frequencies
          if data at f kHz exists:
             # extract relevant data
     ```
  - Remove inconsistent Sv samples at certain frequencies
     - there are three choices: "Accept", "Automated", and "Manually"
     - goal is to retain data that is consistent with how krill backscatter should look like
  - Save outputs as excel files with names like `input_para_data_hake2017-US.xlsx`

**Comment by leewujung** [comment]
> What input files are required

- Echoview NASC exports
  - `x10_18_0.5nmi_10m_cells_50to300m.csv` (from the `fname` field in the organized `.mat` file)
  - `x10_18_10m_cells_50to300m.csv` (from the `file_ID` field in the organized `.mat` file)
  - the exports are organized using script `Display_Proc_exported_transect_data.m` and save to a sheet called ("hake_YEAR")
  - `input_para_data_hake2019-US_bkup.xlsx` contains many years of data in different `hake_YEAR` sheets
- central input excel file
  - with names like `input_para_data_hake2017-US.xlsx`
  - initial spreadsheets generated from Echoview NASC exports
  - manually added (?) spreadsheets for model parameters
  - not sure where the sheet `bio_data` come from, but these look like simple numbers to parameterized the scattering model

**Comment by leewujung** [comment]
> What scattering model(s) are used

- function `DWBAbscat1`: weakly scattering uniformly bent finite inhomogenous body, with segmented g and h along the body
- with orientation average
- with length average

See:
https://github.com/uw-echospace/EchoPro_krill_inversion/blob/main/inversion/functions/SVpredictionALL.m#L56
and
https://github.com/uw-echospace/EchoPro_krill_inversion/blob/main/inversion/Scat_models/zoo_bscat.m#L59-L60
