### ISSUE TITLE
Restructure config YAML files to accommodate multiple species

### ISSUE THREAD

**Issue by leewujung** [uw-echospace/EchoPro#109]
To expand the package to handle krill inversion, we need to restructure the config YAML files. Below are the specifics, which we'll continue to add to in the next few weeks:

### Tasks
- [ ] determine if to keep the current 2 config YAML, one for data sources and one for processing parameters
  - my (@leewujung) vote is yes to keep this separation
- [ ] upgrade the YAML, in particular the data sources one, to use a tree-like structure, so that different categories of inputs are grouped naturally
- [ ] determine where the hake vs krill indicator should go in the above grouping
  - I think we should make it extensible for future expansion to other species

**Comment by leewujung** [comment]
Sounds good.
