### ISSUE TITLE
Refactor functions called in `Survey.__init__`

### ISSUE THREAD

**Issue by leewujung** [uw-echospace/EchoPro#124]
- [x] Remove `input_checks_read.check_existence_of_file`
  - `check_existence_of_file` literally just check if a file exists so there is not need for an extra function
- [ ] Temporarily skip (i.e. commenting out) `_check_init_file` and `_check_survey_year_file` until #125 is addressed
- [ ] Add `exclude_age1` and `source` (rename to `country`) into `survey_year_2019_config.yml`, instead of as separate input arguments for `Survey` init
  - this is important for the sake of reproducibility, so that _everything_ can be rerun using just the yml files
- [x] #127
  - The answer is YES, see #93
- [ ] Create a single `_set_param_from_config` method that is called in `__init__`
  - this function will contain all operations that are now in `_read_config`, `_set_params_from_init`, `_collect_parameters`, and `_convert_str_to_path_obj` (so these methods will be removed)
  - pseudo code below:
    ```python
    def _set_param_from_config(country):
        # Put in place holder for where the config file validators will be used -- see issue #125

        # Use yaml.load to put all params in initialization_config.yml
        #   and all params in survey_year_2019_config.yml in a single output param

        # Do the operations current in _set_params_from_init, including:
        #   np.linspace for setting bio_hake_len_bin
        #   np.linspace for setting bio_hake_age_bin
        #   save country (currently named "source")
        #   compute and set sig_b_coef

        # Convert all string paths to Path objects in params
    ```

**Comment by leewujung** [comment]
Seems like we can close this issue too, since we won't do 
> - [ ] Temporarily skip (i.e. commenting out) `_check_init_file` and `_check_survey_year_file` until https://github.com/uw-echospace/EchoPro/issues/125 is addressed

and 

> - [ ] Add `exclude_age1` and `source` (rename to `country`) into `survey_year_2019_config.yml`, instead of as separate input arguments for `Survey` init
>    * this is important for the sake of reproducibility, so that _everything_ can be rerun using just the yml files

is either done (for `source`/`country`) or is TBD (for `exclude_age1`)?

**Comment by leewujung** [comment]
Confirmed that we can close this issue with the remaining 2 items remaining open until later.
